### ISSUE TITLE
Extension Unable to Recognize Step Definitions Due to Parsing Error

### ISSUE THREAD

**Issue by NickSchudloProdigy** [cucumber/language-service#45]

**Comment by aslakhellesoy** [comment]
@NickSchudloProdigy can you try to update the extension to 1.0.5? The output should now (hopefully) print the paths of files that couuldn't be parsed.

Can you share the output here please?

**Comment by NickSchudloProdigy** [comment]
```
[Info  - 12:15:24 PM] Registering request handler for workspace/didChangeConfiguration failed.
[Info  - 12:15:24 PM] Could not register DidChangeConfigurationNotification: "Unhandled method client/registerCapability" - this is OK
[Info  - 12:15:24 PM] CucumberLanguageServer initialized!
[Info  - 12:15:24 PM] onInitialized
[Info  - 12:15:24 PM] Scheduling reindexing in 0 ms
[Info  - 12:15:25 PM] Found 9 feature file(s)
[Info  - 12:15:25 PM] Found 425 steps in those feature files
[Info  - 12:15:25 PM] Found 9 glue file(s)
[Info  - 12:15:25 PM] Found 0 step definitions in those glue files
[Error - 12:15:25 PM] Errors: Parsing failed
path: e2e/features/Base.feature
[Error - 12:15:25 PM] Errors: Parsing failed
path: e2e/features/FileBrowser.feature
[Error - 12:15:25 PM] Errors: Parsing failed
path: e2e/features/HierarchyView.feature
[Error - 12:15:25 PM] Errors: Parsing failed
path: e2e/features/InspectorView.feature
[Error - 12:15:25 PM] Errors: Parsing failed
path: e2e/features/Prefab.feature
[Error - 12:15:25 PM] Errors: Parsing failed
path: e2e/features/Publishing.feature
[Error - 12:15:25 PM] Errors: Parsing failed
path: e2e/features/RenameAudioFileinEditor.feature
[Error - 12:15:25 PM] Errors: Parsing failed
path: e2e/features/SavingAndLoading.feature
[Error - 12:15:25 PM] Errors: Parsing failed
path: e2e/features/Templates.feature
[Info  - 12:15:25 PM] Built 207 step documents for auto complete
```

And here is an example of one of the feature files it's failing to parse 
![image](https://user-images.githubusercontent.com/74211860/167898453-1f41d7ae-9632-4fcc-aaf6-ce4cfda6bbf7.png)

**Comment by NickSchudloProdigy** [comment]
Oh I realized I had changed my glue config to point to the transpiled .js files for testing. When I changed it back to the .ts files I get this (where the last error is new):
```
[Info  - 12:24:52 PM] Registering request handler for workspace/didChangeConfiguration failed.
[Info  - 12:24:52 PM] Could not register DidChangeConfigurationNotification: "Unhandled method client/registerCapability" - this is OK
[Info  - 12:24:52 PM] CucumberLanguageServer initialized!
[Info  - 12:24:52 PM] onInitialized
[Info  - 12:24:52 PM] Scheduling reindexing in 0 ms
[Info  - 12:24:52 PM] Found 9 feature file(s)
[Info  - 12:24:52 PM] Found 425 steps in those feature files
[Info  - 12:24:52 PM] Found 15 glue file(s)
[Info  - 12:24:52 PM] Found 53 step definitions in those glue files
[Error - 12:24:52 PM] Errors: Parsing failed
path: e2e/features/Base.feature
[Error - 12:24:52 PM] Errors: Parsing failed
path: e2e/features/FileBrowser.feature
[Error - 12:24:52 PM] Errors: Parsing failed
path: e2e/features/HierarchyView.feature
[Error - 12:24:52 PM] Errors: Parsing failed
path: e2e/features/InspectorView.feature
[Error - 12:24:52 PM] Errors: Parsing failed
path: e2e/features/Prefab.feature
[Error - 12:24:52 PM] Errors: Parsing failed
path: e2e/features/Publishing.feature
[Error - 12:24:52 PM] Errors: Parsing failed
path: e2e/features/RenameAudioFileinEditor.feature
[Error - 12:24:52 PM] Errors: Parsing failed
path: e2e/features/SavingAndLoading.feature
[Error - 12:24:52 PM] Errors: Parsing failed
path: e2e/features/Templates.feature
[Error - 12:24:53 PM] Failed to reindex: No parameter type named assetType
```

**Comment by NickSchudloProdigy** [comment]
Removing that defineParameterType seems to have fixed it for me

**Comment by aslakhellesoy** [comment]
Thanks for your help diagnosing this @NickSchudloProdigy. Could you please try with `1.0.7`?

Try restoring your `defineParameterType` - I don't think your step definitions that use `{assetType}` will parse unless you leave it in.

**Comment by NickSchudloProdigy** [comment]
It _does_ seem to have fixed something though, as the syntax highlighting seems to be working properly but there is still no auto complete.
![image](https://user-images.githubusercontent.com/74211860/168083048-048b471f-c0ea-4a72-b89e-d444d05793b6.png)
![image](https://user-images.githubusercontent.com/74211860/168083140-27a10e1f-e727-417d-a948-68823bde4522.png)

**Comment by aurelien-reeves** [comment]
Did you tried defining AssetType in the extension's configuration as described here: https://github.com/cucumber/vscode#cucumberparametertypes?

**Comment by NickSchudloProdigy** [comment]
I just added it and now it seems to think it already knows about the type:
```
[Info  - 10:40:14 AM] Registering request handler for workspace/didChangeConfiguration failed.
[Info  - 10:40:14 AM] Could not register DidChangeConfigurationNotification: "Unhandled method client/registerCapability" - this is OK
[Info  - 10:40:14 AM] CucumberLanguageServer initialized!
[Info  - 10:40:14 AM] onInitialized
[Info  - 10:40:14 AM] Scheduling reindexing in 0 ms
[Info  - 10:40:14 AM] Found 9 feature file(s)
[Info  - 10:40:14 AM] Found 425 steps in those feature files
[Info  - 10:40:14 AM] Found 6 glue file(s)
[Error - 10:40:14 AM] Failed to reindex: There is already a parameter type with name assetType
```

**Comment by aslakhellesoy** [comment]
> Did you tried defining AssetType in the extension's configuration as described here: https://github.com/cucumber/vscode#cucumberparametertypes?

It says:

> Override the cucumber.parameterTypes setting if your Cucumber Expressions are using [Custom Parameter Types](https://github.com/cucumber/cucumber-expressions#custom-parameter-types) that are defined outside your cucumber.glue setting.

In other words - *only* specify it if the parameter type *is not* defined in your own glue code.

**Comment by aslakhellesoy** [comment]
I've released 1.0.9 which just warns if you register an existing parameter type. And fixed a bunch of other bugs.

Can you try again with `v1.0.9`?

**Comment by NickSchudloProdigy** [comment]
@aslakhellesoy Unfortunately it still fails with the same error. It does find it though, but it's not available during indexing?
```
[Info  - 11:54:00 AM] Registering request handler for workspace/didChangeConfiguration failed.
[Info  - 11:54:00 AM] Client does not support client/registerCapability. This is OK.
[Info  - 11:54:00 AM] CucumberLanguageServer initialized!
[Info  - 11:54:00 AM] onInitialized
[Info  - 11:54:00 AM] Scheduling reindexing in 0 ms
[Info  - 11:54:00 AM] Reindexing...
[Info  - 11:54:00 AM] * Found 10 feature file(s) in ["e2e/**/*.feature"]
[Info  - 11:54:00 AM] * Found 459 steps in those feature files
[Info  - 11:54:00 AM] * Found 6 glue file(s) in ["e2e/**/*.feature","e2e/**/*.steps.ts"]
[Info  - 11:54:01 AM] * Found 55 step definitions in those glue files
[Info  - 11:54:01 AM] * Found 1 parameter types in those glue files
[Error - 11:54:01 AM] Failed to reindex: No parameter type named assetType
```

**Comment by aslakhellesoy** [comment]
It's probably a mistake to specify `e2e/**/*.feature` as part of your glue, but the language server should be able to deal with that gracefully. I'll double check.

**Comment by NickSchudloProdigy** [comment]
> Do you know the name of the one parameter type that would have been found under `["e2e/**/*.feature","e2e/**/*.steps.ts"]`? Is it `assetType` or another one?

Yes it is `assetType`. I have only defined one parameter type in this project so far.

**Comment by richwyantoddball** [comment]
I'm having similar issues after installing this. I have one step def and it cannot find it. I've tried the default values for `cucumber.features` and `cucumber.glue`, editing them to be more precise, and moving the classes. Nothing gets recognized. I also don't have the option to create a new step either.

![image](https://user-images.githubusercontent.com/102368447/170142816-691db612-2aec-4ad8-b87f-ee2ead045288.png)

I'm on Mac OSX 12.4 (M1). Below is the pom. Some coordinates referenced are from an example created by using VS Code's Maven extension to make a default Cucumber project.

` <dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>io.cucumber</groupId>
            <artifactId>cucumber-bom</artifactId>
            <version>7.0.0</version>
            <type>pom</type>
            <scope>import</scope>
        </dependency>
        <dependency>
            <groupId>org.junit</groupId>
            <artifactId>junit-bom</artifactId>
            <version>5.8.1</version>
            <type>pom</type>
            <scope>import</scope>
        </dependency>
    </dependencies>
  </dependencyManagement>

  <dependencies>
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>4.11</version>
      <scope>test</scope>
    </dependency>
    
    <dependency> 
      <groupId>org</groupId>
      <artifactId>sikuli</artifactId>
      <version>2.0.6</version>
    </dependency>
   
    
    <dependency>
      <groupId>net.sourceforge.tess4j</groupId>
      <artifactId>tess4j</artifactId>
      <version>5.2.1</version>
    </dependency>
    
    <dependency>
      <groupId>io.cucumber</groupId>
      <artifactId>cucumber-java</artifactId>
      <scope>test</scope>
    </dependency>

    <dependency>
      <groupId>io.cucumber</groupId>
      <artifactId>cucumber-junit-platform-engine</artifactId>
      <scope>test</scope>
    </dependency>

    <dependency>
      <groupId>org.junit.platform</groupId>
      <artifactId>junit-platform-suite</artifactId>
      <scope>test</scope>
    </dependency>

    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter</artifactId>
      <scope>test</scope>
    </dependency>
  </dependencies>

  <build>
    <pluginManagement>
      <plugins>
        
        <plugin>
          <artifactId>maven-clean-plugin</artifactId>
          <version>3.1.0</version>
        </plugin>
        
        <plugin>
          <artifactId>maven-resources-plugin</artifactId>
          <version>3.0.2</version>
        </plugin>
        <plugin>
          <artifactId>maven-compiler-plugin</artifactId>
          <version>3.8.0</version>
        </plugin>
        <plugin>
          <artifactId>maven-surefire-plugin</artifactId>
          <version>3.0.0-M6</version>
        </plugin>
        <plugin>
          <artifactId>maven-jar-plugin</artifactId>
          <version>3.0.2</version>
        </plugin>
        <plugin>
          <artifactId>maven-install-plugin</artifactId>
          <version>2.5.2</version>
        </plugin>
        <plugin>
          <artifactId>maven-deploy-plugin</artifactId>
          <version>2.8.2</version>
        </plugin>
        
        <plugin>
          <artifactId>maven-site-plugin</artifactId>
          <version>3.7.1</version>
        </plugin>
        <plugin>
          <artifactId>maven-project-info-reports-plugin</artifactId>
          <version>3.0.0</version>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.surefire</groupId>
          <artifactId>surefire-junit47</artifactId>
          <version>3.0.0-M6</version>
        </plugin>
      </plugins>
    </pluginManagement>
  </build>

  <reporting>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-surefire-report-plugin</artifactId>
        <version>3.0.0-M6</version>
      </plugin>
    </plugins>
  </reporting>`

**Comment by aslakhellesoy** [comment]
I've fixed a few bugs in `@cucumber/language-server 0.12.3` and the VSCode extension `1.2.1`. @NickSchudloProdigy *hopefully* I've also managed to fix the bug you've seen with reindexing.

Currently, generating step definitions for undefined steps only works if you already have at least one step definition that the language server has identified. This is because it needs to:

1. Determine what programming language to use for generated step definitions
2. Suggest in what file(s) to add it

@richwyantoddball thanks for the `pom.xml` - it's not relevant here as the extension doesn't read it. Please share any [output](https://github.com/cucumber/vscode/blob/main/CONTRIBUTING.md#console-output) from `Cucumber Language Server` in this issue if you still have problems.

This might be improved in a future version.

**Comment by NickSchudloProdigy** [comment]
@aslakhellesoy Hopefully the extra info output can help:
```
[Info  - 9:14:01 AM] Reindexing...
[Info  - 9:14:01 AM] * Found 10 feature file(s) in ["e2e/**/*.feature"]
[Info  - 9:14:01 AM] * Found 459 steps in those feature files
[Info  - 9:14:01 AM] * Found 6 glue file(s) in ["e2e/**/*.steps.ts"]
[Info  - 9:14:01 AM] * Found 1 parameter types in those glue files
[Info  - 9:14:01 AM]   * {assetType} = prefab|audio|image|spine|atlas
[Info  - 9:14:01 AM] * Found 55 step definitions in those glue files
[Info  - 9:14:01 AM] Generating diagnostics
[Error - 9:14:01 AM] Expected a string, but was ["atlas","audio","image","prefab","spine"]
```

This is how `assetType` is defined:
```
defineParameterType({
    name: 'assetType',
    regexp: /prefab|audio|image|spine|atlas/,
    transformer: (s: string) => AssetType[s]
});
```

**Comment by aslakhellesoy** [comment]
Aha insteresting! I should be able to reproduce and fix this now.

**Comment by aslakhellesoy** [comment]
Can you share the definition of `AssetType` as well please?

**Comment by NickSchudloProdigy** [comment]
```
export enum AssetType {
    atlas = 'atlases',
    audio = 'audio',
    image = 'images',
    prefab = 'prefabs',
    spine = 'spine'
}
```

**Comment by aslakhellesoy** [comment]
And finally, some cucumber expressions that use `{assetType}`?

**Comment by NickSchudloProdigy** [comment]
Yeah that is something similar to what I have 
```
Then('The {assetType}( file) {string} exists', async (assetType: AssetType, filename: string): Promise<void> => {
   ...
});
```

**Comment by richwyantoddball** [comment]
Thanks for the response, @aslakhellesoy. I upgraded to the latest version and restarted VS Code. Still getting same issue. Here's the output you asked for:
`
[Info  - 12:28:02 PM] Reindexing...
[Info  - 12:28:02 PM] * Found 0 feature file(s) in ["src/test/**/*.feature","src/test/resources/feature"]
[Info  - 12:28:02 PM] * Found 0 steps in those feature files
[Info  - 12:28:02 PM] * Found 0 glue file(s) in ["src/test/**/*.java","src/test/java/com/oddball/xmlcomparemaven/*.java"]
[Info  - 12:28:02 PM] * Found 0 parameter types in those glue files
[Info  - 12:28:02 PM] * Found 0 step definitions in those glue files
[Info  - 12:28:02 PM] Generating diagnostics
[Info  - 12:28:02 PM] * Built 0 suggestions for auto complete
[Info  - 12:28:02 PM] Unable to generate step definition. Please create one first manually.
`
Relevant settings look like this:
`
    "cucumber.features": [
        "src/test/**/*.feature",
        "src/test/resources/feature"
    ],

    "cucumber.glue": [
        "src/test/**/*.java",
        "src/test/java/com/oddball/xmlcomparemaven/*.java"
    ]
`
This is my stepdef class:
`
package com.oddball.xmlcomparemaven;

import io.cucumber.java.en.Given;

public class StepDefs {

    @Given("This is my step def and its terrific")
    public void this_is_my_step_def_and_its_teriffic() {
        System.out.println("You left out the apostrophe");
    }
    
}
`

This is what I get. Am I doing something wrong?:
![image](https://user-images.githubusercontent.com/102368447/170327614-a0da4fda-bf07-41d3-b064-fe6f94439845.png)

**Comment by aslakhellesoy** [comment]
@richwyantoddball I closed this because I believe #56 addressed the issue originally posted by @NickSchudloProdigy.

Your issue seems to be unrelated. You're not seeing any step definitions, but your logs suggest it's not because of a parsing error, but rather that no feature files or glue files are found from your settings globs. Please create a separate issue for this. Are you on Windows? If so, the bug might be related to that.

**Comment by aslakhellesoy** [comment]
@NickSchudloProdigy the bugfix is released in the VSCode extension version `1.2.3`. Please open a new issue referring this one if the problem persists.

**Comment by NickSchudloProdigy** [comment]
Seems all good on my end! Thanks for working on fixing this 🎉

**Comment by aslakhellesoy** [comment]
Thanks for confirming @NickSchudloProdigy and thanks again for providing all the logs so we could fix this!

**Comment by richwyantoddball** [comment]
Thanks for your efforts, @aslakhellesoy. I'm on a Mac and upgraded to 1.2.3. Still having the same issue. I'll open a separate thread.
